plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - ARTICLES.md
  - BLOGS.md
  - RESSOURCES.md
  - TOP_LECTURE.md
  - TUTOS.md

theme: jekyll-theme-tactile
